### ISSUE TITLE
Is checkpoint_sequential still in torch.utils ?

### ISSUE THREAD

**Issue by warmspringwinds** [prigoyal/pytorch_memonger#16]
Hi,

Thank you for the great repository :)

I have quickly searched and wasn't able to locate the implementation of ```checkpoint_sequential``` in the master branch of the pytorch (which is specified as a dependency for your tutorial).
Is  it still supposed to be there and I just somehow couldn't find it?

Thank you.

**Comment by prigoyal** [comment]
Hi @warmspringwinds , thanks for your query. It is not in the torch.utils yet but the PR is open for it here https://github.com/pytorch/pytorch/pull/4594 

This PR will merge soon and you can track the progress of that PR. :) closing out this task .

**Comment by warmspringwinds** [comment]
@prigoyal Got it. Thank you :)
